"""ROIManager - Gestión de ROIs manuales y automáticos."""
from __future__ import annotations

from typing import Any

import numpy as np


class ROIManager:
    """Gestiona ROIs manuales, automáticos y su conversión."""

    def __init__(self):
        self.primary_rois_text = ""
        self.compare_rois_text = ""
        self.primary_rois_autogenerated = False
        self.compare_rois_autogenerated = False

    def parse_rois_text(self, text: str) -> dict[int, tuple[float, float, float, float]]:
        """Parsea texto ROI a diccionario."""
        rois = {}
        for raw in str(text or "").splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = [p.strip() for p in line.split(",")]
            if len(parts) != 5:
                continue
            try:
                s = int(parts[0])
                cy = float(parts[1])
                cx = float(parts[2])
                ri = float("nan") if parts[3] in ("", "-", "na", "n/a") else float(parts[3])
                ro = float(parts[4])
            except ValueError:
                continue
            rois[s] = (cy, cx, ri, ro)
        return rois

    def format_rois(self, rois: dict[int, tuple[float, float, float, float]]) -> str:
        """Formatea diccionario ROI a texto."""
        lines = []
        for slice_index in sorted(rois):
            cy, cx, r_inner, r_outer = rois[slice_index]
            ri_txt = "-" if not np.isfinite(float(r_inner)) else f"{float(r_inner):.1f}"
            lines.append(f"{slice_index},{cy:.1f},{cx:.1f},{ri_txt},{r_outer:.1f}")
        return "\n".join(lines)

    def rois_from_segmentation(self, seg) -> dict[int, tuple[float, float, float, float]]:
        """Convierte segmentación a ROIs."""
        centers = np.asarray(getattr(seg, "center_per_slice", np.empty((0, 2))), dtype=np.float64)
        inner = np.asarray(getattr(seg, "inner_radius", np.empty((0,))), dtype=np.float64)
        outer = np.asarray(getattr(seg, "outer_radius", np.empty((0,))), dtype=np.float64)
        if centers.ndim != 2 or centers.shape[1] != 2 or inner.shape[0] != centers.shape[0] or outer.shape[0] != centers.shape[0]:
            return {}
        rois = {}
        for slice_index in range(int(centers.shape[0])):
            cy = float(centers[slice_index, 0])
            cx = float(centers[slice_index, 1])
            r_inner = float(inner[slice_index])
            r_outer = float(outer[slice_index])
            if not np.isfinite(cy) or not np.isfinite(cx) or not np.isfinite(r_outer) or r_outer <= 0.0:
                continue
            rois[int(slice_index)] = (cy, cx, r_inner if np.isfinite(r_inner) else float("nan"), r_outer)
        return rois

    def is_roi_valid(self, roi: tuple[float, float, float, float] | None) -> bool:
        """Valida un ROI."""
        if roi is None or len(roi) != 4:
            return False
        cy, cx, r_inner, r_outer = (float(v) for v in roi)
        if not np.isfinite(cy) or not np.isfinite(cx):
            return False
        if not np.isfinite(r_outer) or r_outer <= 0.0:
            return False
        if np.isfinite(r_inner) and r_inner < 0.0:
            return False
        if np.isfinite(r_inner) and r_outer <= r_inner:
            return False
        return True

    def get_primary_rois(self) -> dict[int, tuple[float, float, float, float]]:
        """Obtiene ROIs primarios parseados."""
        return self.parse_rois_text(self.primary_rois_text)

    def get_compare_rois(self) -> dict[int, tuple[float, float, float, float]]:
        """Obtiene ROIs de comparación parseados."""
        return self.parse_rois_text(self.compare_rois_text)

    def set_primary_rois(self, rois: dict[int, tuple[float, float, float, float]], autogenerated: bool = False):
        """Establece ROIs primarios."""
        self.primary_rois_text = self.format_rois(rois)
        self.primary_rois_autogenerated = autogenerated

    def set_compare_rois(self, rois: dict[int, tuple[float, float, float, float]], autogenerated: bool = False):
        """Establece ROIs de comparación."""
        self.compare_rois_text = self.format_rois(rois)
        self.compare_rois_autogenerated = autogenerated

    def clear_primary_rois(self):
        """Limpia ROIs primarios."""
        self.primary_rois_text = ""
        self.primary_rois_autogenerated = False

    def clear_compare_rois(self):
        """Limpia ROIs de comparación."""
        self.compare_rois_text = ""
        self.compare_rois_autogenerated = False

    def get_roi_summary(self, source: str = "primary") -> dict[str, Any]:
        """Retorna resumen de ROIs."""
        if source == "primary":
            text = self.primary_rois_text
            autogenerated = self.primary_rois_autogenerated
        else:
            text = self.compare_rois_text
            autogenerated = self.compare_rois_autogenerated
        rois = self.parse_rois_text(text)
        return {
            "source": source,
            "n_rois": len(rois),
            "autogenerated": autogenerated,
            "text_preview": text[:100] + "..." if len(text) > 100 else text,
        }
